### ISSUE TITLE
Error in md2_hash.py prevents any operations from starting.  Python 3.6.1

### ISSUE THREAD

**Issue by brentpayton** [Ekultek/Dagon#1]
Encountered on a fully-patched 64-bit Windows 10 system with Python 3.6.1 (and only that version).  

The installation process provided on Github was followed for the package:  clone the repo then use pip to install dependencies.

No errors are returned when pip runs.

Any command issued to dagon,py returns the same error, shown below.

```
c:\temp\dagon>python dagon.py -h
Traceback (most recent call last):
  File "dagon.py", line 7, in <module>
    from bin.attacks.bruteforce.bf_attack import bruteforce_main
  File "c:\temp\dagon\bin\attacks\bruteforce\bf_attack.py", line 5, in <module>
    from lib.settings import FUNC_DICT
  File "c:\temp\dagon\lib\settings.py", line 7, in <module>
    from lib.algorithms.hashing_algs import *
  File "c:\temp\dagon\lib\algorithms\hashing_algs.py", line 4, in <module>
    from thirdparty.md2 import md2_hash
  File "c:\temp\dagon\thirdparty\md2\md2_hash.py", line 150
    print md2h(readchars(f)) + "\t" + name
             ^
SyntaxError: invalid syntax
```

**Comment by brentpayton** [comment]
Installing Python 2.7.13 addressed this problem.  I suggest updating your docs OR scolding me if I missed this requirement.

**Comment by Ekultek** [comment]
First, release. I'll verify that `python 2.7.x` is required for this application, thanks, I'll do my best to make it compatible for all `python` versions as well.

**Comment by brentpayton** [comment]
No problem.  I aim to be helpful.

**Comment by Ekultek** [comment]
Made a check just to be sure https://github.com/Ekultek/Dagon/commit/a8be23ad0d6fda9dcf2edacedf8859fc5c820103
