### ISSUE TITLE
dagon can't execute

### ISSUE THREAD

**Issue by rendykyh** [Ekultek/Dagon#118]
# Issue/idea:
when python dagon.py execute,
Traceback (most recent call last):
  File "dagon.py", line 11, in <module>
    from bin.verify_hashes.verify import verify_hash_type
  File "/root/dagon/bin/verify_hashes/verify.py", line 5, in <module>
    from lib.settings import (
  File "/root/dagon/lib/settings.py", line 15, in <module>
    from lib.github.create_issue import (
ImportError: cannot import name dagon_failure

# Any idea what caused this to happen?
no idea

# Application running specifics:
  - Installation method? 
 git clone
  
  - Operating system and architecture: 
kali Linux wsl windows 10 64  

  - Dagon version information:
I can't do that/ I don't know what version
  
  - Hash you where attempting to crack:
no

  - Exact commands used:
 no

# Algorithm(s) used:
no

# Exact error message:
up there

**Comment by Ekultek** [comment]
fixed via https://github.com/Ekultek/Dagon/commit/7441b56cd0cd7a98484f6c8d5b2cf7f5e35a0993
