### ISSUE TITLE
optparse and python 3.x

### ISSUE THREAD

**Issue by Ekultek** [Ekultek/Dagon#16]
To fix this I'm going to do this:

```
try:
    import optparse
except ImportError:
    import argparse as optparse
```

**Comment by delirious-lettuce** [comment]
`argparse` and `optparse` are not the same thing at all...

```python
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import argparse as optparse
>>> parser = optparse.OptionParser(usage="dagon [c|v|V|l] HASH|HASH-LIST --bruteforce [OPTS]")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'argparse' has no attribute 'OptionParser'

```

**Comment by Ekultek** [comment]
Yeah I was just playing with this. So here's what going to happen. I'm not going to replace `optparse` (_yet_) if someone wants to write the options and make them compatible they can, i'll slowly convert everything else to be compatible but until then `optparse` is gonna stay, I'll leave this open though.

**Comment by Ekultek** [comment]
@delirious-lettuce I assigned this to you, it's yours to work on how you see fit
