### ISSUE TITLE
Issue with --update

### ISSUE THREAD

**Issue by arismelachroinos** [Ekultek/Dagon#36]
# Issue/idea:
Running command --update gives error.

# Any idea what caused this to happen?
No

# Application running specifics:
  - Installation method? 
Cloned in /root/dagon
  
  - Operating system and architecture: 
Latest Kali 64 bit
  
  - Dagon version information:
v1.12.24.43(dev)
  
# Exact error message:
python dagon.py --update
Dagon .. Advanced Hash Manipulation v1.12.24.43(dev)
Clone: https://github.com/ekultek/dagon.git

[23:19:34 INFO] Update in progress..
Traceback (most recent call last):
  File "dagon.py", line 180, in <module>
    update_status = update_system()
  File "/root/dagon/lib/settings.py", line 355, in update_system
    updater = subprocess.check_output("git pull origin master")
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by Ekultek** [comment]
Go into the `dagon` directory and run `ls -a` post all the output please

**Comment by arismelachroinos** [comment]
root@User:~/dagon# ls -a
.         bin       .git        legal   optparse  README.md
..        dagon.py  .github     lib     os        requirements.txt
bf-dicts  docs      .gitignore  md5sum  random    thirdparty

**Comment by Ekultek** [comment]
Fixed via https://github.com/Ekultek/Dagon/commit/6dbf7a76f9ba114a5f95656cf18dc2a16b454c1c
