### ISSUE TITLE
Compatability with Python version 3.x

### ISSUE THREAD

**Issue by Ekultek** [Ekultek/Dagon#5]
Need people to find the non-compatible stuff of the application, I've done my best to make it compatible but i don't know all the differences and such, so please find it for me, thank you.

**Comment by Ekultek** [comment]
print function and raw_input along with some imports should be taken care of in the next push

**Comment by delirious-lettuce** [comment]
I know importing `from __future__ import print_function` is easy, but how are you getting rid of `raw_input`? Something like [`six`](https://pypi.python.org/pypi/six)?

Also, `optparse` does not exist for Python 3. `argparse` is in the standard library (2 & 3) but there are also third party libraries like [`click`](http://click.pocoo.org/5/).

**Comment by Ekultek** [comment]
`optparse` isn't in 3.x?

**Comment by Ekultek** [comment]
@delirious-lettuce example: https://github.com/Ekultek/Dagon/blob/master/lib/settings.py#L169

**Comment by delirious-lettuce** [comment]
https://docs.python.org/2/library/optparse.html

**Comment by Ekultek** [comment]
Well fuck...

**Comment by Ekultek** [comment]
Idk if this will work but #16 might fix it

**Comment by delirious-lettuce** [comment]
#16 will not fix it. `argparse` and `optparse` are not the same thing...

**Comment by Ekultek** [comment]
@delirious-lettuce as mentioned, we'll slowly push everything over from `optparse` to `argparse` so for now it's still going to require 2.7.x

**Comment by delirious-lettuce** [comment]
@Ekultek ,

No problem, I just wanted to mention it as it's a speed bump in the way of 2/3 compatibility.

I'm actually just about to send you a PR for something else, hopefully you don't mind.

**Comment by Ekultek** [comment]
I'm about to update some stuff so go ahead and we'll see what you got

**Comment by delirious-lettuce** [comment]
haha pressure is on!
