### ISSUE TITLE
Hash guarantee (.aiPOIXET)

### ISSUE THREAD

**Issue by Dagon-Project** [Ekultek/Dagon#53]
Dagon has failed to crack given hash: `.aiPOIXET9GG/`.

This was attempted on `2017-08-11 18:08:05.690794`..

Commands that were used during failure:
`['dagon.py', '-c', '.aiPOIXET9GG/', '--bruteforce', '-w', '/usr/share/dict/american-english']`

Algorithm attempted: `None`

**Comment by Ekultek** [comment]
This is a test.
