### ISSUE TITLE
Hash guarantee ()

### ISSUE THREAD

**Issue by Dagon-Project** [Ekultek/Dagon#55]
Dagon has failed to crack given hash: ``.

This was attempted on `2017-08-13 16:20:55.841384`..

Commands that were used during failure:
`['dagon.py', '-c', '', '--bruteforce', '-w', '/usr/share/dict/american-english']`

Algorithm attempted: `None`

**Comment by Ekultek** [comment]
Looks like you forgot to add a hash, correct syntax: `dagon.py -c <HASH> -w <WORDLIST>`
