### ISSUE TITLE
Unhandled Exception (VsDTH)

### ISSUE THREAD

**Issue by Dagon-Project** [Ekultek/Dagon#68]
Exception:
`Exception`
Issue data: `((), '')`

Running detail:
OS: `Linux-4.10.0-32-generic-x86_64-with-Ubuntu-17.04-zesty`
Hash used: `098f6bcd4621d373cade4e832627b4f6`
CMD args: `['dagon.py', '-c', '098f6bcd4621d373cade4e832627b4f6', '--bruteforce']`

**Comment by Ekultek** [comment]
This is just a test
