### ISSUE TITLE
Unhandled Exception HTTPError(PcZnz)

### ISSUE THREAD

**Issue by Dagon-Project** [Ekultek/Dagon#69]
Exception:
`HTTPError`
Issue data: `('()', '')`

Running detail:
OS: `Linux-4.10.0-32-generic-x86_64-with-Ubuntu-17.04-zesty`
Hash used: `2237a2260e9438e14e8bced36f6cbcf4`
CMD args: `['./dagon.py', '-c', '2237a2260e9438e14e8bced36f6cbcf4', '--bruteforce', '-D', 'downloads']`

**Comment by Ekultek** [comment]
test
