### ISSUE TITLE
Hash guarantee ('/home/ha)

### ISSUE THREAD

**Issue by Dagon-Project** [Ekultek/Dagon#76]
Dagon has failed to crack given hash: `'/home/hacked/Desktop/LamFamily-94:44:52:4D:89:C6.cap`.

This was attempted on `2017-10-21 06:02:31.379046`..

Commands that were used during failure:
`['dagon.py', '-c', "'/home/hacked/Desktop/LamFamily-94:44:52:4D:89:C6.cap", '--bruteforce', '-w', '/root/cupp/lam.txt']`

Algorithm attempted: `None`

**Comment by Ekultek** [comment]
This is not a hash, it’s an SSID `cap` file. Closing this as invalid
