### ISSUE TITLE
Hash guarantee (/root/Dow)

### ISSUE THREAD

**Issue by Dagon-Project** [Ekultek/Dagon#83]
Dagon has failed to crack given hash: `/root/Downloads/nclteams/cracking5_hashes2.txt`.

This was attempted on `2017-11-18 14:04:49.042219`..

Commands that were used during failure:
`['dagon.py', '-v', '/root/Downloads/nclteams/cracking5_hashes2.txt']`

Algorithm attempted: `None`

**Comment by Ekultek** [comment]
I need the hash, I’ll leave this open for 24 hours and then I’ll close it if no hash is provided
