### ISSUE TITLE
Hash guarantee (./tzXhGRz)

### ISSUE THREAD

**Issue by Dagon-Project** [Ekultek/Dagon#88]
Dagon has failed to crack given hash: `./tzXhGRzJQl2ctwjAvnpWatW5ct`.

This was attempted on `2017-12-12 16:18:33.536465`..

Commands that were used during failure:
`['dagon.py', '-c', './tzXhGRzJQl2ctwjAvnpWatW5ct', '--bruteforce']`

Algorithm attempted: `None`

**Comment by Ekultek** [comment]
I have no idea what this is.

**Comment by Ekultek** [comment]
Been doing research, this is not a hash.
