### ISSUE TITLE
Hash guarantee (/root/Des)

### ISSUE THREAD

**Issue by Dagon-Project** [Ekultek/Dagon#91]
Dagon has failed to crack given hash: `/root/Desktop/-cleaned.cap`.

This was attempted on `2017-12-22 21:15:18.684349`..

Commands that were used during failure:
`['dagon.py', '-c', '/root/Desktop/-cleaned.cap', '--bruteforce', '-w', 'Dagon-bfdict-vfODTGK.txt']`

Algorithm attempted: `None`

**Comment by Ekultek** [comment]
Not designed to crack cap files, use aircrack.
