### ISSUE TITLE
Hash guarantee (cfacfbaba)

### ISSUE THREAD

**Issue by Dagon-Project** [Ekultek/Dagon#99]
Dagon has failed to crack given hash: `cfacfbabadf7abf8ab8fa2a0b5aaa5e1aca0a2`.

This was attempted on `2018-02-08 13:07:30.500332`..

Commands that were used during failure:
`['dagon.py', '-v', 'cfacfbabadf7abf8ab8fa2a0b5aaa5e1aca0a2']`

Algorithm attempted: `None`

**Comment by Ekultek** [comment]
I don't think this is a hash. Where did you get it from?

**Comment by Ekultek** [comment]
No reply
